In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy as sp

In [3]:
df = pd.read_csv('C:/1. Yuke/Master 1st semester/MMAI5000_AI/ToyotaCorolla.csv')

In [4]:
df

,Id,Model,Price,Age_08_04,Mfg_Month,Mfg_Year,KM,Fuel_Type,HP,Met_Color,...,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Parking_Assistant,Tow_Bar
0,1,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13500,23,10,2002,46986,Diesel,90,1,...,1,1,0,0,0,1,0,0,0,0
1,2,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13750,23,10,2002,72937,Diesel,90,1,...,0,1,0,0,0,1,0,0,0,0
2,3,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13950,24,9,2002,41711,Diesel,90,1,...,0,1,0,0,0,1,0,0,0,0
3,4,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,14950,26,7,2002,48000,Diesel,90,0,...,0,1,0,0,0,1,0,0,0,0
4,5,TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors,13750,30,3,2002,38500,Diesel,90,0,...,1,1,0,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1431,1438,TOYOTA Corolla 1.3 16V HATCHB G6 2/3-Doors,7500,69,12,1998,20544,Petrol,86,1,...,1,1,0,1,1,1,0,0,0,0
1432,1439,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,10845,72,9,1998,19000,Petrol,86,0,...,0,1,0,0,1,1,0,0,0,0
1433,1440,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,8500,71,10,1998,17016,Petrol,86,0,...,0,1,0,0,0,1,0,0,0,0
1434,1441,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,7250,70,11,1998,16916,Petrol,86,1,...,0,0,0,0,0,1,0,0,0,0
1435,1442,TOYOTA Corolla 1.6 LB LINEA TERRA 4/5-Doors,6950,76,5,1998,1,Petrol,110,0,...,0,1,0,0,0,0,0,0,0,0

In [5]:
df.describe()

,Id,Price,Age_08_04,Mfg_Month,Mfg_Year,KM,HP,Met_Color,Automatic,CC,...,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Parking_Assistant,Tow_Bar
count,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.00000,...,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000
mean,721.555014,10730.824513,55.947075,5.548747,1999.625348,68533.259749,101.502089,0.674791,0.055710,1576.85585,...,0.561978,0.977716,0.146240,0.256964,0.300139,0.770195,0.204735,0.145543,0.002786,0.277855
std,416.476890,3626.964585,18.599988,3.354085,1.540722,37506.448872,14.981080,0.468616,0.229441,424.38677,...,0.496317,0.147657,0.353469,0.437111,0.458478,0.420854,0.403649,0.352770,0.052723,0.448098
min,1.000000,4350.000000,1.000000,1.000000,1998.000000,1.000000,69.000000,0.000000,0.000000,1300.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,361.750000,8450.000000,44.000000,3.000000,1998.000000,43000.000000,90.000000,0.000000,0.000000,1400.00000,...,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,721.500000,9900.000000,61.000000,5.000000,1999.000000,63389.500000,110.000000,1.000000,0.000000,1600.00000,...,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,1081.250000,11950.000000,70.000000,8.000000,2001.000000,87020.750000,110.000000,1.000000,0.000000,1600.00000,...,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000
max,1442.000000,32500.000000,80.000000,12.000000,2004.000000,243000.000000,192.000000,1.000000,1.000000,16000.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
predictors = ['Age_08_04', 'KM', 'Fuel_Type', 'HP', 'Met_Color', 'Automatic', 'CC', 
              'Doors', 'Quarterly_Tax', 'Weight']
outcome = 'Price'

In [6]:
pip install pathlib

Collecting pathlib
  Downloading pathlib-1.0.1-py3-none-any.whl (14 kB)
Installing collected packages: pathlib
Successfully installed pathlib-1.0.1
Note: you may need to restart the kernel to use updated packages.

In [8]:

pip install dmba

Collecting dmba
  Downloading dmba-0.2.4-py3-none-any.whl (11.8 MB)
Requirement already satisfied: scipy in c:\users\kryst\anaconda3\lib\site-packages (from dmba) (1.7.1)
Requirement already satisfied: scikit-learn in c:\users\kryst\appdata\roaming\python\python39\site-packages (from dmba) (1.1.1)
Requirement already satisfied: numpy in c:\users\kryst\anaconda3\lib\site-packages (from dmba) (1.20.3)
Requirement already satisfied: matplotlib in c:\users\kryst\anaconda3\lib\site-packages (from dmba) (3.4.3)
Requirement already satisfied: pandas in c:\users\kryst\anaconda3\lib\site-packages (from dmba) (1.3.4)
Collecting graphviz
  Downloading graphviz-0.20.3-py3-none-any.whl (47 kB)
Requirement already satisfied: pillow>=6.2.0 in c:\users\kryst\anaconda3\lib\site-packages (from matplotlib->dmba) (8.4.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\kryst\anaconda3\lib\site-packages (from matplotlib->dmba) (1.3.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\kryst\anaconda3\lib\site-packages (from matplotlib->dmba) (2.8.2)
Requirement already satisfied: cycler>=0.10 in c:\users\kryst\anaconda3\lib\site-packages (from matplotlib->dmba) (0.10.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\kryst\anaconda3\lib\site-packages (from matplotlib->dmba) (3.0.4)
Requirement already satisfied: six in c:\users\kryst\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib->dmba) (1.16.0)
Requirement already satisfied: pytz>=2017.3 in c:\users\kryst\anaconda3\lib\site-packages (from pandas->dmba) (2021.3)
Requirement already satisfied: joblib>=1.0.0 in c:\users\kryst\anaconda3\lib\site-packages (from scikit-learn->dmba) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\kryst\anaconda3\lib\site-packages (from scikit-learn->dmba) (2.2.0)
Installing collected packages: graphviz, dmba
Successfully installed dmba-0.2.4 graphviz-0.20.3
Note: you may need to restart the kernel to use updated packages.

In [9]:
pip install sklearn

Requirement already satisfied: sklearn in c:\users\kryst\anaconda3\lib\site-packages (0.0.post4)
Note: you may need to restart the kernel to use updated packages.

In [10]:
pip install statsmodels

Requirement already satisfied: statsmodels in c:\users\kryst\anaconda3\lib\site-packages (0.12.2)
Requirement already satisfied: numpy>=1.15 in c:\users\kryst\anaconda3\lib\site-packages (from statsmodels) (1.20.3)
Requirement already satisfied: scipy>=1.1 in c:\users\kryst\anaconda3\lib\site-packages (from statsmodels) (1.7.1)
Requirement already satisfied: pandas>=0.21 in c:\users\kryst\anaconda3\lib\site-packages (from statsmodels) (1.3.4)
Requirement already satisfied: patsy>=0.5 in c:\users\kryst\anaconda3\lib\site-packages (from statsmodels) (0.5.2)
Requirement already satisfied: pytz>=2017.3 in c:\users\kryst\anaconda3\lib\site-packages (from pandas>=0.21->statsmodels) (2021.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\kryst\anaconda3\lib\site-packages (from pandas>=0.21->statsmodels) (2.8.2)
Requirement already satisfied: six in c:\users\kryst\anaconda3\lib\site-packages (from patsy>=0.5->statsmodels) (1.16.0)
Note: you may need to restart the kernel to use updated packages.